### ISSUE TITLE
Pay button should be hidden is no amount owed on My Account view_order page

### ISSUE THREAD

**Issue by kiel-abraham** [NetoECommerce/Skeletal#338] opened 2018-02-02 03:32 UTC
/templates/customer/view_order/order.template.html

Suggested fix
```
[%show_order id:'[@order_id@]'%]
    [%param *header%]
        [%if [@amount_owed@]%]
            <button class="btn btn-success pull-right" onclick="location.href='[%URL page:'account' type:'pay_order' qs:'action=paynow' id:'[@order_id@]'%][%END URL%]'"><i class="fa fa-check icon-white"></i> Pay Now</button>
        [%/if%]
    [%/param%]
[%/show_order%]
```

**Comment by matt-downs** [comment] 2018-02-02 03:37
This should also be updated too:
https://github.com/NetoECommerce/Skeletal/blob/8c8138ac664c67dbfcec354c454569c149df49b0/src/templates/customer/nr_view_order/order.template.html#L24-L30

The button is in the body of the function - a duplicate of the same button will display for each orderline lol

**Closed** 2018-03-15 06:33 UTC
